steps:

 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/pundit-frontend', '-f', 'Dockerfile_frontend']

 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/pundit-backend', '-f', 'Dockerfile_backend']

